name: tickets
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  draw_your_image: 0.2.0
  cupertino_icons: 1.0.5
  get: 4.3.8
  flutter_spinkit: 5.1.0
  google_fonts: 2.2.0
  # uni_links: 0.5.1
  carousel_slider: 4.0.0
  dio: 4.0.4
  liquid_pull_to_refresh: 3.0.1
  cached_network_image: 3.2.0
  animate_do: 2.1.0
  get_storage: 2.0.3
  flutter_easyloading: 3.0.5
  app_settings: 4.1.8
  flutter_secure_storage: 5.0.2
  shared_preferences: 2.0.15
  blobs: 2.0.0
  lottie: 1.3.0
  flutter_staggered_grid_view: 0.6.2
  cloud_firestore: 3.4.6
  firebase_core: 1.21.0
  animated_text_kit: 4.2.2
  fluttericon: 2.0.0
  firebase_storage: 10.3.7
  firebase_database: 9.1.3
  image_downloader_web: 1.0.2
  share_plus: 6.3.1
  path_provider: 2.0.11
  modal_bottom_sheet: 2.1.2
  persistent_bottom_nav_bar: 5.0.2
  flutter_colorpicker: 1.0.3
  screenshot: 1.2.3
  firebase_auth: 3.11.2
  # flutter_map: 3.0.0
  geolocator: 8.2.1
  flutter_map: 0.14.0
  date_time_picker: 2.1.0
  flutter_datetime_picker: 1.5.1
  emoji_picker_flutter: 1.5.0
  image_picker: 0.8.6
  pull_to_refresh: 2.0.0
  flutter_slidable: 2.0.0
  firebase_core_platform_interface: 4.5.1
  firebase_messaging: 13.0.4
  awesome_notifications: 0.7.4+1
  internet_connection_checker: 1.0.0+1
  pretty_qr_code: 2.0.2
  add_2_calendar: 2.2.3
  geoflutterfire2: 2.3.12
  qr_code_scanner: 1.0.1
  sizer: 2.0.15
  webview_flutter: 4.0.1
  pixels: 1.0.1
  image_painter: 0.5.0
  photo_view: 0.14.0
  xl: 0.9.1
  uuid: 3.0.7
  # flutter_yandex_ads: 1.0.0+1
  google_mobile_ads: 2.3.0
  remove_background: 0.0.1
  flutter_painter: 1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/images/
